name: Run Action on Folder Change and PR Updates

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_folder_change:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Check for changes in the folder
        id: changes
        run: |
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep '^path/to/folder/'; then
            echo "Folder has changed."
            echo "::set-output name=folder_changed::true"
          else
            echo "No folder changes detected."
            echo "::set-output name=folder_changed::false"
          fi

      - name: Cache folder change state
        uses: actions/cache@v4
        with:
          path: folder_change_flag
          key: folder-change-${{ github.event.pull_request.number }}
          restore-keys: |
            folder-change-${{ github.event.pull_request.number }}

      - name: Set folder change flag
        if: steps.changes.outputs.folder_changed == 'true'
        run: echo "changed" > folder_change_flag/changed.txt

      - name: Check if folder change flag exists
        id: check_flag
        run: |
          if [ -f folder_change_flag/changed.txt ]; then
            echo "::set-output name=flag_exists::true"
          else
            echo "::set-output name=flag_exists::false"
          fi

      - name: Continue running based on flag
        if: |
          steps.changes.outputs.folder_changed == 'true' ||
          steps.check_flag.outputs.flag_exists == 'true'
        run: |
          echo "Folder has changed previously or just now, running action."

      # Add your specific job steps here
      - name: Example Step
        run: echo "This runs when folder changes or every commit in the PR after that."
