name: Run Action on Folder Change and PR Updates

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "test/**" # Specify the folder you're interested in here

  workflow_run:
    workflows: ["Run Action on Folder Change and PR Updates"]
    types:
      - completed

jobs:
  folder_change_job:
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Add your specific job steps here
      - name: Example Step
        run: echo "This runs when folder changes or every commit in the PR"
